# Server configurations
server:
  host: "localhost"
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5

# Database credentials
mongodb:
  url: "mongodb+srv://challengeUser:WUMglwNBaydH8Yvu@challenge-xzwqd.mongodb.net/getir case-study?retryWrites=true"
  tablename: "records"
  connecttimeoutms: 30000